global:
  enabled: true
  default-layout: "blue"

world-settings: #example worlds
  lobby:
    enabled: true
    layout: "red"
  survival:
    enabled: true
    layout: "green"
  minigames:
    enabled: false # completely disable scoreboard here

layouts:
  blue:
    title: "<#0079FF>ʏᴏᴜʀѕᴇʀᴠᴇʀɴᴀᴍᴇ</#0079FF>"
    lines:
      - "⌚ %server_time_kk:mm% | %server_time_dd/MM%"
      - ""
      - "<#0079FF>%player_name%</#0079FF>"
      - " <#0079FF>|</#0079FF> ʙᴀʟᴀɴᴄᴇ: $%vault_eco_balance_formatted%"
      - " <#0079FF>|</#0079FF> ᴋɪʟʟѕ: %statistic_player_kills%"
      - " <#0079FF>|</#0079FF> ᴅᴇᴀᴛʜѕ: %statistic_deaths%"
      - " <#0079FF>|</#0079FF> ᴡᴏʀʟᴅ: %player_world%"
      - ""
      - "<#0079FF>Server Name</#0079FF>"
      - " <#0079FF>|</#0079FF> ᴏɴʟɪɴᴇ: %server_online%/%server_max_players%"
      - " <#0079FF>|</#0079FF> ᴊᴏɪɴѕ: %server_unique_joins% "
      - ""
      - "ᴘʟᴀʏᴇʀ.ѕᴇʀᴠᴇʀ "

  pink:
    title: "<#FF39EB>ʏᴏᴜʀѕᴇʀᴠᴇʀɴᴀᴍᴇ</#FF39EB>"
    lines:
      - "⌚ %server_time_kk:mm% | %server_time_dd/MM%"
      - ""
      - "<#FF39EB>%player_name%</#FF39EB>"
      - " <#FF39EB>|</#FF39EB> ʙᴀʟᴀɴᴄᴇ: $%vault_eco_balance_formatted%"
      - " <#FF39EB>|</#FF39EB> ᴋɪʟʟѕ: %statistic_player_kills%"
      - " <#FF39EB>|</#FF39EB> ᴅᴇᴀᴛʜѕ: %statistic_deaths%"
      - " <#FF39EB>|</#FF39EB> ᴡᴏʀʟᴅ: %player_world%"
      - ""
      - "<#FF39EB>Server Name</#FF39EB>"
      - " <#FF39EB>|</#FF39EB> ᴏɴʟɪɴᴇ: %server_online%/%server_max_players%"
      - " <#FF39EB>|</#FF39EB> ᴊᴏɪɴѕ: %server_unique_joins%"
      - ""
      - "ᴘʟᴀʏᴇʀ.ѕᴇʀᴠᴇʀ"

  green:
    title: "<#23FF4B>ʏᴏᴜʀѕᴇʀᴠᴇʀɴᴀᴍᴇ</#23FF4B>"
    lines:
      - "⌚ %server_time_kk:mm% | %server_time_dd/MM%"
      - ""
      - "<#23FF4B>%player_name%</#23FF4B>"
      - " <#23FF4B>|</#23FF4B> ʙᴀʟᴀɴᴄᴇ: $%vault_eco_balance_formatted%"
      - " <#23FF4B>|</#23FF4B> ᴋɪʟʟѕ: %statistic_player_kills%"
      - " <#23FF4B>|</#23FF4B> ᴅᴇᴀᴛʜѕ: %statistic_deaths%"
      - " <#23FF4B>|</#23FF4B> ᴡᴏʀʟᴅ: %player_world%"
      - ""
      - "<#23FF4B>Server Name</#23FF4B>"
      - " <#23FF4B>|</#23FF4B> ᴏɴʟɪɴᴇ: %server_online%/%server_max_players%"
      - " <#23FF4B>|</#23FF4B> ᴊᴏɪɴѕ: %server_unique_joins%"
      - ""
      - "ᴘʟᴀʏᴇʀ.ѕᴇʀᴠᴇʀ"